### PR TITLE
add extra err check for analyzeCss result

### LINKED ISSUE #580: analyzeCss module doesn't work in node 4.2
I noticed that analyzeCss doesn't work well with node 4.2.
The subcommand returns err="" and a working results object, so it still goes into the error handling section.

### PR DESCRIPTION
**Pull request by ingoclaro**
closes #580 

In node4 executing analyzeCss returns err === "". Previous code was taking this as an error (since it's !== null), I added more checks to avoid this.

### CODE REVIEW

**Comment by ingoclaro** [comment]
I noticed that this is the only module that calls runScript, so maybe the bug is over there... I'm not sure how to add a test for that function since it executes an external command.

**Comment by macbre** [comment]
`runScript` passes a string to `err` argument of the callback only when there's an error - [the code](https://github.com/macbre/phantomas/blob/1f6b3d92621c64a26e9571d9acd4f9fe1d912fe3/core/phantomas.js#L849-L855). An empty string there means that `JSON.parse` failed.

Is `runScript: JSON parsing failed!` error logged in your case?

**Comment by ingoclaro** [comment]
I don't get JSON parsing errors in the logs, and an object is returned in results.

**Comment by macbre** [comment]
This one is quite mysterious. The code simply can not return both an error string and a result of parsing JSON-encoded string. Are you sure that you're running phantomas with `--debug` option?

**Comment by ingoclaro** [comment]
very sure, I get indeed the following log:

```
runScript: pid #46321 done (took 112 ms)
```

[here](https://gist.github.com/ingoclaro/ad3f01f2bc7c79a91ef6) you can see the full log, this has this patch already applied.

**Comment by macbre** [comment]
Can you revert the patch and provide the full log of the same phantomas run? This issue looks quite strange to me and I'd like to find the root cause here. Thanks :)

**Comment by ingoclaro** [comment]
sure, added another file to the same gist. As you can see it reports cssParsingErrors, also no JSON parsing errors

**Comment by ingoclaro** [comment]
regardless of this issue, what do you think of the error handling proposal? I could submit a separate PR with that, and it would provide more clarity on the error itself, since now it returns stderr instead of expressing that the json failed to parse.

**Comment by macbre** [comment]
Let's return either `stderr` (if not empty) or `ex` (from JSON parsing try / catch block) as an error.

**Comment by ingoclaro** [comment]
ok, this is funny, now I do get the JSON parsing error :S....
Weird.
At least now we see the same issue ;), it's not closing the issue though... :(
Do you prefer a separate PR for this code?

**Comment by macbre** [comment]
Looks good, no need for a separate PR.

Thanks for debugging and submitting a fix!

**Pull request merged**
