### PR TITLE
Upgrading ascii-table version

### PR DESCRIPTION
**Pull request by sorensen**
Addresses array issue in ascii-table: sorensen/ascii-table#9

### CODE REVIEW

**Comment by macbre** [comment]
@sorensen, thanks

**Comment by macbre** [comment]
After the upgrade `ascii-table` stopped displaying zeros. Any idea why?

```
.-----------------------------------------------------------------------------------------------------------.
| Report from 3 run(s) for <http://example.com/> using phantomas v1.9.0                                     |
|-----------------------------------------------------------------------------------------------------------|
|             Metric             |     min      |     max      |   average    |    median    |    stddev    |
|--------------------------------|--------------|--------------|--------------|--------------|--------------|
| requests                       |            1 |            1 |            1 |            1 |              |
| gzipRequests                   |              |              |              |              |              |
| postRequests                   |              |              |              |              |              |
| httpsRequests                  |              |              |              |              |              |
...
```

**Comment by sorensen** [comment]
Yes, I've just fixed the issue in `0.0.8`. Sorry about that.

**Comment by sorensen** [comment]
I've added another PR. https://github.com/macbre/phantomas/pull/497

**Comment by macbre** [comment]
Great, thanks!

**Pull request merged**
