### PR TITLE
New metric proposal "synchronousXHR"

### PR DESCRIPTION
**Pull request by gmetais**
This metric is meant to count the number of **not asynchronous** XMLHttpRequest (https://github.com/gmetais/YellowLabTools/issues/138).

While adding this metric, I found two problems. The test I added reveals both problems, this is why the Travis tests will break.
1. the `ajaxRequests` metric does not catch all kind of ajax requests, is it broken?
2. synchronous XHR are never marked as received, as you can see in the `requestsWithTimeout` offenders. The reason is because PhantomJS doesn't trigger the `onResourceReceived` event for synchronous XHR calls (https://github.com/ariya/phantomjs/issues/11284).

I will open two new issues. Should I correct the tests so that the new metric can be merged safely?

### CODE REVIEW

**Comment by macbre** [comment]
Let's fix #619 and #620 before merging this one. Thanks for suggesting and implementing this.

**Comment by EFF** [comment]
Yeah right, thanks for the work! I share @macbre's opinion on fixing the issues first, then fixing and writing tests if necessary.

**Comment by macbre** [comment]
@gmetais, I'll try to apply yout patch when #726 is merged.

**Comment by macbre** [comment]
@gmetais, I've ported your changes to #734. Thanks!

**Pull request closed without merging**
