### PR TITLE
Puppeteer in docker

### LINKED ISSUE #741: Prepare a Docker image with Puppeteer installed
See #707 

* https://hub.docker.com/r/buildkite/puppeteer
* https://github.com/GoogleChrome/puppeteer/blob/master/.ci/node8/Dockerfile.linux
* https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-on-alpine

### PR DESCRIPTION
**Pull request by macbre**
Resolves #741 

```
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
phantomas                   latest              a4f93009c5c8        4 minutes ago       426MB
```

```
  phantomas:browser Using binary from: /usr/bin/chromium-browser +2s
  phantomas:browser Original browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/73.0.3683.103 Safari/537.36 +7ms
```

## TODO list

* [x] build a working Docker image with Chromium and a matching version of puppeteer
* [x] ~use [`zenika/alpine-chrome` base Docker image](https://hub.docker.com/r/zenika/alpine-chrome/)~ image weights 739 MB vs 515MB when built "manually"
* [x] use GitHub Actions for integration tests
* [x] use the latest puppeteer and Chromium 85
* [x] make all tests pass / decide which minor features can be disabled for now:
* [x] `--devices.html`
* [ ] `performanceTimingDNS`

### CODE REVIEW

**Comment by macbre** [comment]
```
HeadlessChrome/73.0.3683.103
Error: Navigation failed because browser has disconnected!
```

https://github.com/woahbase/alpine-chromium

**Comment by gmetais** [comment]
Will Phantomas run inside or outside of the Docker container?

**Comment by macbre** [comment]
I'm thinking about both scenarios being supported :slightly_smiling_face:

**Comment by gmetais** [comment]
Ok, this is smart.

**Comment by macbre** [comment]
https://github.com/puppeteer/puppeteer/releases/tag/v3.0.0 - there's even a Firefox support :slightly_smiling_face:

**Comment by macbre** [comment]
```
  /devices.html
    ✓ should be generated
    ✓ should have "viewport" metric properly set
  /devices.html (with --phone)
    ✗ should be generated 
        » No error should be thrown: got TypeError: Cannot read property 'viewport' of undefined // /home/macbre/src/git/phantomas/node_modules/vows/lib/assert/macros.js:31
    ✗ should have "userAgent" metric properly set 
      TypeError: results.getMetric is not a function 
      at Object.batch.(anonymous function).(anonymous function) (/home/macbre/src/git/phantomas/test/integration-test.js:75:31) 
      at runTest (/home/macbre/src/git/phantomas/node_modules/vows/lib/vows.js:136:26) 
      at EventEmitter.<anonymous> (/home/macbre/src/git/phantomas/node_modules/vows/lib/vows.js:81:9) 
      at EventEmitter.emit (events.js:203:15) 
      at EventEmitter.options.Emitter.emit (/home/macbre/src/git/phantomas/node_modules/vows/lib/vows.js:241:24) 
      at /home/macbre/src/git/phantomas/node_modules/vows/lib/vows/context.js:32:52 
      at Object.env.callback (/home/macbre/src/git/phantomas/node_modules/vows/lib/vows/context.js:46:29) 
      at promise.then.catch.err (/home/macbre/src/git/phantomas/test/integration-test.js:48:23)
```

**Comment by macbre** [comment]
Via GitHub Actions (`HeadlessChrome/83.0.4103.0`):

> ✗ Errored » 397 honored ∙ 31 broken ∙ 8 errored (41.415s) 

In the Docker container (`HeadlessChrome/83.0.4103.116`):

> ✗ Errored » 423 honored ∙ 5 broken ∙ 8 errored (33.139s) 

Locally (`HeadlessChrome/83.0.4103.0`):

> ✗ Errored » 423 honored ∙ 5 broken ∙ 8 errored (40.534s) 
>
>   /devices.html (with --XXX)
>
>   /timing.html
> ...
>    ✗ should have "performanceTimingDNS" metric properly set 
>        » expected 0, 
>  	got	 NaN (strictEqual) // /home/macbre/src/git/phantomas/node_modules/vows/lib/assert/macros.js:14

**Comment by macbre** [comment]
Tests in the Docker container:

> ✗ Broken » 435 honored ∙ 1 broken (28.485s) 

```
REPOSITORY                                           TAG                 IMAGE ID            CREATED                  SIZE
macbre/phantomas                                     latest              9da1515e5ad8        Less than a second ago   724MB
node                                                 14-slim             01b9467e04f4        4 days ago               167MB
```

**Comment by macbre** [comment]
@gmetais - we're almost there, tests are not passing with just one test case broken :tada:

**Comment by macbre** [comment]
Tests run on GitHub Actions fail. However, they do pass when run inside our Docker container. Will fix that later.

Travis checks do pass too.

**Pull request merged**
