### PR TITLE
Add woff2 detection

### PR DESCRIPTION
**Pull request by gmetais**
Detect woff2 files as a font

### CODE REVIEW

**Comment by macbre** [comment]
@gmetais - let's move this ticket to `phantomas-v2` that will work on top of Chromium / puppeteer.

**Comment by gmetais** [comment]
@macbre Sure! PhantomJS was stuck with woff 1.
What are your plans for v2? And how can I help?

**Comment by macbre** [comment]
@gmetais - thanks! An overview / TODO list is in #744. I'll start with preparing a working Docker image and then we can jump into fixing tests / modules that report metrics.

**Comment by macbre** [comment]
@gmetais - can you please rebase this PR using the latest phantomas' `master`. And tests would be great :slightly_smiling_face:

**Comment by gmetais** [comment]
Hi @macbre, did you mean branch `devel`?

**Comment by macbre** [comment]
@gmetais, yes

**Comment by gmetais** [comment]
I'm closing this one, cause it was created from GitHub's GUI. Opening a new one in a minute.

**Pull request closed without merging**
