### PR TITLE
Fix bug for random Size metrics 

### PR DESCRIPTION
**Pull request by AdriwanKenoby**
I try to log htmlSize, bodySize, contentLength, ... These metrics had always random values !

### CODE REVIEW

**Comment by macbre** [comment]
Thanks for the PR, however please update your clone before submitting it.

**Comment by AdriwanKenoby** [comment]
@macbre 
I already have the v5.11.1, not the devel branch but i thought it works. I have last version for phantomjs too i.e 2.1.1.
So what I need to update ?

**Comment by macbre** [comment]
@AdriwanKenoby, you need to sync your fork with this repository `devel` branch - https://help.github.com/articles/syncing-a-fork/

**Comment by AdriwanKenoby** [comment]
I am already on the `devel` branch
screenshot

**Comment by macbre** [comment]
`AdriwanKenoby  wants to merge 69 commits into master from devel` - it seems that you want to merge two branches in the upstream. When creating a pull requests please select your fork and a correct branch.

**Comment by AdriwanKenoby** [comment]
I do not want to fork the project if not necessary ... So what 's wrong with the master branch if it is synchronyse with devel ? Maybe i am just stupid and don't know use git.

**Comment by macbre** [comment]
Well, forking is necessary to submit pull requests to projects on GitHub :)

**Comment by AdriwanKenoby** [comment]
Ok.. What does i need to use your project if the npm install is not suffisant. I don't understand sorry

**Comment by gmetais** [comment]
@AdriwanKenoby are you trying to report a bug (open an issue), or to fix a bug (open a pull request)?

Cause it seems to me you're just trying to report a bug and you clicked the wrong button.

**Comment by AdriwanKenoby** [comment]
@macbre 
Yeah I just want to report a bug. Sorry for confusion. I thought it was already fix and you say me to update the phantomas version or follow and other branch...

**Comment by macbre** [comment]
@AdriwanKenoby, no worries :)

**Pull request closed without merging**
