### PR TITLE
Fix lazy load. Get scr via getAttribute.

### PR DESCRIPTION
**Pull request by r-kovalenko**
It was a problem with getting the right value, it could have been the URI of page in scr after getting instead of empty string. We have to use attribute instead of propertie.

### CODE REVIEW

**Comment by macbre** [comment]
@r-kovalenko, thanks for the fix!

**Comment by gmetais** [comment]
Hi!

I'm deeply sorry, but I preferred the old version, that was providing the complete urls in the offenders. 
Now we can have incomplete urls such as:

```
/img/image.png
../img/image.png
//www.domain.com/img/image.png
```

I would vote for a revert to the previous version, for consistency across offenders (and because I liked the way it was !).

@r-kovalenko, can't we keep the following change: 
```if (src === null '' || /^data:/.test(src)) {```
```if (src === null || src === '' || /^data:/.test(src)) {```
to avoid problems when an `` has no `src` attribute, 

but remove the following change:
```src = images[i].src;```
```src = images[i].getAttribute('src');```

?

**Comment by r-kovalenko** [comment]
I think the check must be more coplicated. If we get src via .src and and it is empty - browser interperts it like current url of page. Thats why only check src === null woun't resolve problem.

**Comment by macbre** [comment]
Let's start with preparing a test cases where these extra checks are needed. It will make regressions detection much easier.

**Pull request merged**
